### ISSUE TITLE
注册中心consul开启了权限控制(ACL)，如何注册micro服务

### ISSUE THREAD

**Issue by hsxy0820** [micro-in-cn/questions#1]
- 解决办法： 设置环境变量CONSUL_HTTP_TOKEN
(以下为k8s配置文件的sample)
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: utils-srvtest
  name: utils-srvtest-deployment
  namespace: micro
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: utils-srvtest
  template:
    metadata:
      labels:
        app: utils-srvtest
    spec:
      containers:
        - image: xxx/k12-utils-srv
          imagePullPolicy: Always
          name: utils-srvtest
          env:
            - name: CONSUL_HTTP_TOKEN
              value: 7b8560ce-6eed-3aa9-7c9e-488cc36xxxxx
          workingDir: /log/utils-srvtest/
          command: ["/bin/bash"]
          args: ["-c","utils-api --registry=consul --registry_address=consultest:8500 --register_ttl=30 --register_interval=20 1>>/log/utils-srvtest/$(POD_NAME).log 2>&1"]
```
