### ISSUE TITLE
如果用pm2部署 micro api 网关

### ISSUE THREAD

**Issue by metauro** [micro-in-cn/questions#73]
现在的自己用micro写的微服务都是build后通过pm2部署，但是网关是通过命令行启动的，不知道怎么用pm2

**Comment by metauro** [comment]
已解决,使用以下脚本去pm2 start即可
```yaml
apps:
  - name: micro-gateway
    script: ./config.toml # 随意写个文件路径
    interpreter: micro
    interpreter_args: api
    instances: 1
    exec_mode: fork
    env: 
      MICRO_API_HANLDER: rpc
      MICRO_REGISTRY: etcd
```
